// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type User struct {
	ID          int64       `json:"id"`
	Name        string      `json:"name"`
	Strength    pgtype.Int4 `json:"strength"`
	Inteligence pgtype.Int4 `json:"inteligence"`
	Focus       pgtype.Int4 `json:"focus"`
	Speed       pgtype.Int4 `json:"speed"`
	Endurance   pgtype.Int4 `json:"endurance"`
}
