// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: query.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createUser = `-- name: CreateUser :one
INSERT INTO users (
    name,
    strength,
    inteligence,
    focus,
    speed,
    endurance
) VALUES (
    $1, $2, $3, $4, $5, $6
)
RETURNING id, name, strength, inteligence, focus, speed, endurance
`

type CreateUserParams struct {
	Name        string      `json:"name"`
	Strength    pgtype.Int4 `json:"strength"`
	Inteligence pgtype.Int4 `json:"inteligence"`
	Focus       pgtype.Int4 `json:"focus"`
	Speed       pgtype.Int4 `json:"speed"`
	Endurance   pgtype.Int4 `json:"endurance"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.Name,
		arg.Strength,
		arg.Inteligence,
		arg.Focus,
		arg.Speed,
		arg.Endurance,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Strength,
		&i.Inteligence,
		&i.Focus,
		&i.Speed,
		&i.Endurance,
	)
	return i, err
}

const deleteUser = `-- name: DeleteUser :exec
DELETE FROM users
WHERE id = $1
`

func (q *Queries) DeleteUser(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, deleteUser, id)
	return err
}

const getUser = `-- name: GetUser :one
SELECT id, name, strength, inteligence, focus, speed, endurance
FROM users
WHERE id = $1
`

func (q *Queries) GetUser(ctx context.Context, id int64) (User, error) {
	row := q.db.QueryRow(ctx, getUser, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Strength,
		&i.Inteligence,
		&i.Focus,
		&i.Speed,
		&i.Endurance,
	)
	return i, err
}

const listUsers = `-- name: ListUsers :many
SELECT id, name, strength, inteligence, focus, speed, endurance
FROM users
ORDER BY id
`

func (q *Queries) ListUsers(ctx context.Context) ([]User, error) {
	rows, err := q.db.Query(ctx, listUsers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []User
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Strength,
			&i.Inteligence,
			&i.Focus,
			&i.Speed,
			&i.Endurance,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateUserStats = `-- name: UpdateUserStats :one
UPDATE users
SET
    strength    = COALESCE($2, strength),
    inteligence = COALESCE($3, inteligence),
    focus       = COALESCE($4, focus),
    speed       = COALESCE($5, speed),
    endurance   = COALESCE($6, endurance)
WHERE id = $1
RETURNING id, name, strength, inteligence, focus, speed, endurance
`

type UpdateUserStatsParams struct {
	ID          int64       `json:"id"`
	Strength    pgtype.Int4 `json:"strength"`
	Inteligence pgtype.Int4 `json:"inteligence"`
	Focus       pgtype.Int4 `json:"focus"`
	Speed       pgtype.Int4 `json:"speed"`
	Endurance   pgtype.Int4 `json:"endurance"`
}

func (q *Queries) UpdateUserStats(ctx context.Context, arg UpdateUserStatsParams) (User, error) {
	row := q.db.QueryRow(ctx, updateUserStats,
		arg.ID,
		arg.Strength,
		arg.Inteligence,
		arg.Focus,
		arg.Speed,
		arg.Endurance,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Strength,
		&i.Inteligence,
		&i.Focus,
		&i.Speed,
		&i.Endurance,
	)
	return i, err
}
